# Generated by Django 4.2.1 on 2023-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Total',
            new_name='Sales',
        ),
    ]
